# .github/workflows/docker-publish.yml
name: Build and Push Docker Image

# Trigger the workflow on push events to the main or dev branch
on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2.3.4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: Emmanuel
          password: 20045122

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: Emmanuel/dictionary-backend:dev
